### PR TITLE
fix: update cxx language standard

### PR DESCRIPTION
**Pull request by okwasniewski**
This PR updates cxx language standard to fix building on latest version of React Native

Address: https://github.com/mrousavy/react-native-blob-jsi-helper/issues/15

### CODE REVIEW

**Comment by hannojg** [comment]
I think a cleaner solution might be to use `install_modules_dependencies` ?

**Comment by okwasniewski** [comment]
Yeah good suggestion, @hannojg updated

**Comment by mrousavy** [comment]
letsgooo!

**Comment by iBotPeaches** [comment]
May we get a version released with this? It does fix #15 in our testing after pulling in the patch locally.

**Pull request merged**
