### PR TITLE
feat: #10 support react native 0.71

### PR DESCRIPTION
**Pull request by mlecoq**
Inspired by https://github.com/mrousavy/react-native-mmkv/pull/480

### CODE REVIEW

**Comment by kesha-antonov** [comment]
Need this for RN 0.71

**Comment by hannojg** [comment]
Hey, we are looking into this, thank you so much for the effort!

**Comment by hannojg** [comment]
Changes looking good on my end. I say we merge that and do a new major release with breaking change to be only compatible with react native 0.71 onwards.

**Comment by mrousavy** [comment]
Thanks for your PR! ❤️

**Pull request merged**
